window.QUESTION_PACKS = [
  {
    id: "personal-starter",
    name: "個人版 36 題",
    license: "free",
    status: "selected-draft",
    description: "以熟悉度與提問深度分成 Lv1-Lv4 的 MVP 題包。",
    questions: [
      { id: "personal-001", mode: "friends", level: "Lv1", category: "人際關係", text: "你猜猜看，我最想跟誰吃一頓飯？" },
      { id: "personal-002", mode: "friends", level: "Lv1", category: "人生觀", text: "你猜猜看，如果我明天財富自由，第一件事會做什麼？" },
      { id: "personal-003", mode: "friends", level: "Lv1", category: "興趣嗜好", text: "你猜猜看，我人生最浪費錢的興趣是什麼？" },
      { id: "personal-004", mode: "friends", level: "Lv1", category: "消費觀", text: "你猜猜看，我最容易衝動買的是哪一類東西？" },
      { id: "personal-005", mode: "friends", level: "Lv1", category: "生活習慣", text: "你猜猜看，我最討厭哪種天氣？" },
      { id: "personal-006", mode: "friends", level: "Lv1", category: "生活習慣", text: "你猜猜看，我最常熬夜是因為什麼？" },
      { id: "personal-007", mode: "friends", level: "Lv1", category: "生活習慣", text: "你猜猜看，我手機裡最多的是什麼照片？" },
      { id: "personal-008", mode: "friends", level: "Lv1", category: "工作與學習", text: "你猜猜看，我最不擅長哪種事情？" },
      { id: "personal-009", mode: "friends", level: "Lv1", category: "興趣嗜好", text: "你猜猜看，我人生最容易迷上的東西是什麼類型？" },
      { id: "personal-010", mode: "friends", level: "Lv1", category: "生活習慣", text: "你猜猜看，如果放假一整天，我大概率在幹嘛？" },
      { id: "personal-011", mode: "acquaintance", level: "Lv2", category: "人際關係", text: "你猜猜看，我最受不了哪種人？" },
      { id: "personal-012", mode: "acquaintance", level: "Lv2", category: "人生觀", text: "你猜猜看，我其實很在意什麼？" },
      { id: "personal-013", mode: "acquaintance", level: "Lv2", category: "人際關係", text: "你猜猜看，我對朋友最重視什麼？" },
      { id: "personal-014", mode: "acquaintance", level: "Lv2", category: "人際關係", text: "你猜猜看，我最容易因為什麼生氣？" },
      { id: "personal-015", mode: "acquaintance", level: "Lv2", category: "人生觀", text: "你猜猜看，我最大的優點是什麼？" },
      { id: "personal-016", mode: "acquaintance", level: "Lv2", category: "人生觀", text: "你猜猜看，我最大的缺點是什麼？" },
      { id: "personal-017", mode: "acquaintance", level: "Lv2", category: "人生觀", text: "你猜猜看，我最害怕變成什麼樣的人？" },
      { id: "personal-018", mode: "acquaintance", level: "Lv2", category: "消費觀", text: "你猜猜看，我對錢最真實的看法是什麼？" },
      { id: "personal-019", mode: "acquaintance", level: "Lv2", category: "人生觀", text: "你猜猜看，我最不願意妥協的是什麼？" },
      { id: "personal-020", mode: "acquaintance", level: "Lv2", category: "人際關係", text: "你猜猜看，我最討厭被別人誤會什麼？" },
      { id: "personal-021", mode: "acquaintance", level: "Lv3", category: "人生觀", text: "你猜猜看，我學生時代最常被老師唸什麼？" },
      { id: "personal-022", mode: "acquaintance", level: "Lv3", category: "人生觀", text: "你猜猜看，我人生最後悔的一件事是什麼類型？" },
      { id: "personal-023", mode: "acquaintance", level: "Lv3", category: "人生觀", text: "你猜猜看，我人生最得意的一件事是什麼？" },
      { id: "personal-024", mode: "acquaintance", level: "Lv3", category: "人生觀", text: "你猜猜看，我曾經做過最衝動的決定是什麼？" },
      { id: "personal-025", mode: "acquaintance", level: "Lv3", category: "人際關係", text: "你猜猜看，我最感謝遇到哪一種人？" },
      { id: "personal-026", mode: "acquaintance", level: "Lv3", category: "人生觀", text: "你猜猜看，我人生哪個階段變化最大？" },
      { id: "personal-027", mode: "acquaintance", level: "Lv3", category: "人生觀", text: "你猜猜看，我最希望回到幾歲？" },
      { id: "personal-028", mode: "acquaintance", level: "Lv3", category: "人生觀", text: "你猜猜看，我人生最大的轉捩點是什麼？" },
      { id: "personal-029", mode: "couple", level: "Lv4", category: "人生觀", text: "你猜猜看，我其實最缺乏的是什麼？" },
      { id: "personal-030", mode: "couple", level: "Lv4", category: "人生觀", text: "你猜猜看，我最怕失去什麼？" },
      { id: "personal-031", mode: "couple", level: "Lv4", category: "人生觀", text: "你猜猜看，如果我只剩一年，我第一個放棄的是什麼？" },
      { id: "personal-032", mode: "couple", level: "Lv4", category: "人生觀", text: "你猜猜看，我最想彌補的遺憾是什麼類型？" },
      { id: "personal-033", mode: "couple", level: "Lv4", category: "人生觀", text: "你猜猜看，我最大的心魔是什麼？" },
      { id: "personal-034", mode: "couple", level: "Lv4", category: "人生觀", text: "你猜猜看，我最希望別人怎麼記得我？" },
      { id: "personal-035", mode: "couple", level: "Lv4", category: "人生觀", text: "你猜猜看，我十年後最有可能變成什麼樣子？" },
      { id: "personal-036", mode: "couple", level: "Lv4", category: "人際關係", text: "你猜猜看。\n\n你對我的印象裡，\n\n哪一件事情其實完全猜錯了？" }
    ]
  },
  {
    id: "candidate-general",
    name: "通用候選題庫",
    license: "free",
    status: "candidate",
    description: "先前產生的通用題目先保留為候選池，未來再挑選是否進入預設題庫。",
    questions: [
      { id: "candidate-001", mode: "friends", category: "生活習慣", text: "如果今天突然多出兩小時空檔，你覺得我最可能拿來做什麼？" },
      { id: "candidate-002", mode: "friends", category: "興趣嗜好", text: "我最近最容易被哪一類影片、文章或話題吸引？" },
      { id: "candidate-003", mode: "friends", category: "消費觀", text: "我最願意花小錢提升生活品質的是什麼？" },
      { id: "candidate-004", mode: "friends", category: "人際關係", text: "我不熟的人做什麼會讓我比較快放下戒心？" },
      { id: "candidate-005", mode: "friends", category: "工作與學習", text: "我做事比較像先規劃再開始，還是邊做邊修？" },
      { id: "candidate-006", mode: "friends", category: "生活習慣", text: "我壓力大時最容易出現哪個小習慣？" },
      { id: "candidate-007", mode: "friends", category: "興趣嗜好", text: "如果週末只能選一種活動，我會選室內還是戶外？" },
      { id: "candidate-008", mode: "friends", category: "人生觀", text: "如果人生是一款遊戲，我現在最想升級哪個能力值？" },
      { id: "candidate-009", mode: "friends", category: "消費觀", text: "我最近一次覺得買得很值得的東西可能是什麼？" },
      { id: "candidate-010", mode: "acquaintance", category: "工作與學習", text: "我遇到困難時，最希望別人給我哪一種支援？" },
      { id: "candidate-011", mode: "acquaintance", category: "人際關係", text: "我遇到衝突時比較會沉默、解釋，還是轉移話題？" },
      { id: "candidate-012", mode: "acquaintance", category: "生活習慣", text: "我最不能忍受生活中哪一種混亂？" },
      { id: "candidate-013", mode: "acquaintance", category: "興趣嗜好", text: "哪一件事會讓我忘記時間？" },
      { id: "candidate-014", mode: "acquaintance", category: "消費觀", text: "我買東西時最容易被哪種理由說服？" },
      { id: "candidate-015", mode: "acquaintance", category: "人生觀", text: "我現在最想把生活調整成什麼樣子？" },
      { id: "candidate-016", mode: "acquaintance", category: "人際關係", text: "我什麼時候會覺得自己真的被理解？" },
      { id: "candidate-017", mode: "acquaintance", category: "工作與學習", text: "我最怕遇到哪一種合作方式？" },
      { id: "candidate-018", mode: "acquaintance", category: "人生觀", text: "我最害怕把時間浪費在哪一件事上？" },
      { id: "candidate-019", mode: "couple", category: "愛情觀", text: "我覺得一段關係裡最重要的安全感來自什麼？" },
      { id: "candidate-020", mode: "couple", category: "愛情觀", text: "我比較在意儀式感、陪伴時間，還是實際行動？" },
      { id: "candidate-021", mode: "couple", category: "愛情觀", text: "吵架後，我最希望對方先做什麼？" },
      { id: "candidate-022", mode: "couple", category: "人際關係", text: "我最不擅長拒絕哪一種請求？" },
      { id: "candidate-023", mode: "couple", category: "人生觀", text: "我希望五年後的自己保留現在的哪一點？" },
      { id: "candidate-024", mode: "couple", category: "消費觀", text: "如果突然得到一筆獎金，我第一個想怎麼用？" },
      { id: "candidate-025", mode: "couple", category: "愛情觀", text: "我理想中的約會最不可缺少的是什麼？" },
      { id: "candidate-026", mode: "couple", category: "人生觀", text: "我認為真正的自由比較接近什麼狀態？" },
      { id: "candidate-027", mode: "couple", category: "愛情觀", text: "我最容易被哪一種貼心打動？" },
      { id: "candidate-028", mode: "friends", category: "生活習慣", text: "我早上醒來後第一個固定動作可能是什麼？" },
      { id: "candidate-029", mode: "friends", category: "興趣嗜好", text: "我最冷門、但自己很喜歡的小喜好是什麼？" },
      { id: "candidate-030", mode: "acquaintance", category: "工作與學習", text: "我在學新東西時最常卡住的點是什麼？" },
      { id: "candidate-031", mode: "acquaintance", category: "消費觀", text: "我會為了省錢犧牲便利嗎？大概到什麼程度？" },
      { id: "candidate-032", mode: "couple", category: "愛情觀", text: "我在關係裡最需要被提醒或被照顧的是什麼？" },
      { id: "candidate-033", mode: "couple", category: "人生觀", text: "我希望別人記得我哪一種樣子？" },
      { id: "candidate-034", mode: "friends", category: "工作與學習", text: "如果可以立刻升級一項能力，我會選什麼？" },
      { id: "candidate-035", mode: "acquaintance", category: "人際關係", text: "我最欣賞朋友身上的哪一種特質？" },
      { id: "candidate-036", mode: "couple", category: "消費觀", text: "我覺得共同花錢最需要先講清楚的是什麼？" }
    ]
  }
];
